### PR TITLE
respect http proxy configured in environment variables

### PR DESCRIPTION
**Pull request by wolfoo2931**
Like discussed in the GitHub issue there are no unit tests for this line. And because I've no write access to a PivNet instance the integration tests must be executed.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wolfoo2931 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=10)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=10) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by robdimsdale** [comment]
@wolfoo2931 could you sign the CLA as linked above? This should be good to merge at that point.

Thanks,
Rob

**Comment by wolfoo2931** [comment]
CLA should be signed now

**Comment by pivotal-issuemaster** [comment]
@wolfoo2931 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=10)!

**Comment by robdimsdale** [comment]
There were some merge conflicts but I believe this should work as expected. We can't really test it so please let us know if it doesn't work.

Thanks for the contribution!

Rob

**Pull request merged**
