### PR TITLE
adding ability to ignore ssl validation

### PR DESCRIPTION
**Pull request by calebwashburn**
Thank you for contributing to the go-pivnet API library!

- Have you made this pull request to the `develop` branch? yes
- Have you [run the tests locally](https://github.com/pivotal-cf/go-pivnet#running-the-tests)? yes

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@calebwashburn Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=3)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=3) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@calebwashburn Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/go-pivnet&pullRequestId=3)!

**Comment by robdimsdale** [comment]
@caleb Washburn thanks for this. I'm happy to merge it in. Just out of curiosity what custom endpoint are you targeting that doesn't have valid SSL configured?

**Comment by calebwashburn** [comment]
This is due to using pivnet behind corporate proxy server that is injecting a "decrypt" cert.  also testing with the pivnet councourse resource as well.

**Comment by robdimsdale** [comment]
Cool thanks, I figured it was something like that.

**Pull request merged**
